### PR TITLE
Ignore state of shift key in keyboard commands

### PR DESCRIPTION
**Pull request by danieljharvey**
Hello!

I hope you are well. Thanks for this tool, I use it every day and I have a nice time. Every now and then I think it's broken and doesn't listen to me, and I realised it's because I have the caps lock on, so this PR is an entirely selfish contribution to stop the keyboard commands caring about the state of the shift key so I can avoid footgunning myself several times a day.

Thanks!

### CODE REVIEW

**Comment by i-am-tom** [comment]
As a fellow computer-misuser, I'm happy about this 👌

**Comment by i-am-tom** [comment]
Having a second look, could we just remove the `, shift: _` from the pattern-match entirely?

**Comment by danieljharvey** [comment]
Aye, would probably make things cleaner.

**Comment by kritzcreek** [comment]
Thanks, removed the shift pattern matches in bf90dd733ff5f346b3ef28953644a79e0e455768

**Comment by kritzcreek** [comment]
Released as 2.7.0

**Pull request closed without merging**
