### PR TITLE
Add include option

### PR DESCRIPTION
**Pull request by garyb**
I'm super smart. Opened this as a PR on my own repo about half an hour ago.

Follows the same conventions as `pulp`'s `--include` / `-I`.

### CODE REVIEW

**Comment by kritzcreek** [comment]
haha :D Would it be better to split the directories inside the argument parser and make Options hold a list of strings?

**Comment by garyb** [comment]
It probably would yeah, but I'm also stumbling around not knowing what I'm doing with yargs so wasn't sure how to incorporate that! I can take another look though.

**Comment by kritzcreek** [comment]
Don't worry about it I can do it aswell. I think it's just pulling the let from main into the runY lambda

**Comment by kritzcreek** [comment]
So this is good to go and ready to be released? :) I'll give it a spin locally and then publish

**Comment by garyb** [comment]
Yep, I think so! I did some rudimentary testing locally.

**Comment by kritzcreek** [comment]
Made some slight adjustments in https://github.com/kRITZCREEK/pscid/commit/1b0e64d466514de8c25a3c2cf1de3a0e25b054c4 and pushed as 1.7.0. Thanks again!

**Pull request merged**
