### PR TITLE
update 0.15.7

### LINKED ISSUE #77: Connection refused error upon starting `pscid`
First of all: pscid is awesome! Thank you for making it!

Right now, on my machine, running `pscid` fails with the following error:

```
Starting purs ide server
/nix/store/dvzm9gdda8a6vbjra63zqly74jkvdp3j-pscid-2.9.3/lib/node_modules/pscid/output/Effect.Aff/foreign.js:532
                throw util.fromLeft(step);
                ^

Error: connect ECONNREFUSED ::1:15740
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 15740
}

Node.js v18.14.2
```

Interestingly, a `purs ide server` process with the correct port configured is spawned:

```
> ps aux | grep purs
theuser    2816343  0.0  0.1 1074468872 27776 pts/8 Sl  18:30   0:00 purs ide server -p 15740 --output-directory output
```

A few months ago, running `pscid` *just worked* (I just revisited an older project of mine). My first thought was that this may have something to do with my firewall but disabling that does not change anything. Also, `nc` works:

```
> nc localhost 15740
bla
{"result":"Parsing the command failed with:\nError in $: Failed reading: not a valid json value at 'bla'\nCommand: bla","resultType":"error"}
```

To be honest, I'm a bit blank on what the problem may be. Maybe `pscid` tries to connect too fast to the `purs ide` server? Help would be much appreciated!

### PR DESCRIPTION
**Pull request by semio**
updated package-set to 0.15.7:

- change .js files to ES modules
- adapt to changes in dependencies

I tried `spago run` and `npm run start`,  it seems to be working well, and also fixed #77 

The purescript-suggest package is not in the package-set, so I also forked and updated the package, and added it in packages.dhall. 

@kritzcreek please kindly review the changes and let me know if there are problems. If it looks good I could make a PR to purscript-suggest too

### CODE REVIEW

**Review by kritzcreek — APPROVED** [review]
Changes look great in general, thank you! I added a couple more updates over here https://github.com/semio/pscid/pull/1.

If you can PR the updates to purescript-suggest we can get this merged and released.

**Comment by semio** [comment]
ok, thanks! will make PR to purescript-suggest soon.

**Comment by semio** [comment]
@kritzcreek on updating purescript-suggest, I can easily setup the package with `spago init` and it just worked and passed all test cases. But when I tried to update the dependencies in bower.json, I got many conflicts about package versions. I am not sure what's the best way to update bower dependencies. Would you suggest? If you think that it's easier for you to just make the PR yourself, please do :)

**Comment by kritzcreek** [comment]
Hey, sorry for the late response. If `suggest` builds as is and works fine, I don't think we need to do anything there. I just wanted to make sure we were relying on a version from `suggest`s main branch.

In that case I'll merge and make a release.

**Comment by kritzcreek** [comment]
Okay, it looks like suggest _did_ need some updates. So I made a PR over there, let's see how things go.

**Comment by kritzcreek** [comment]
The changes got merged to `purescript-suggest` but they didn't end up being tagged and published to the registry. Just having the commit on master was good enough for me though, so I updated a few more dependencies and published `v2.10.0` which includes all your changes. Could you please verify that thew new release also fixes the network issue from #77? Thanks!

**Comment by semio** [comment]
Yes, `v2.10.0` works for me, no network issue. Thanks for making a release!

**Pull request merged**
