### PR TITLE
use spago for deps and build

### PR DESCRIPTION
**Pull request by justinwoo**
Does this project need to use bower?

### CODE REVIEW

**Comment by justinwoo** [comment]
If you'd like this in some kind of form. Not entirely sure what all goes on with the build/install process.

**Comment by justinwoo** [comment]
Updated this finally

**Comment by kritzcreek** [comment]
Sorry, I totally missed your force push. I'll try to resolve the conflicts and get this merged if I can push to your branch.

**Comment by kritzcreek** [comment]
Merged in #64

**Comment by justinwoo** [comment]
:+1:

**Comment by kritzcreek** [comment]
Thanks!

**Pull request closed without merging**
